services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
    #  - "8081:8081"
    volumes:
      # - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro # Windows
      # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro # Windows
      - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro # MAC/LINUX
      - ${HOME}/.aspnet/dev-certs/https:/home/app/.aspnet/https:ro # MAC/LINUX
    networks:
      - dms-net

  web-ui:
    build:
      context: ./web-ui
    ports:
      - "80:80"
    networks:
      - dms-net

networks:
  dms-net:
    driver: bridge
