version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      # plattformabhängige Volume-Mounts
      - type: bind
        source: ${APPDATA:-${HOME}/.microsoft/usersecrets}
        target: /home/app/.microsoft/usersecrets:ro
        read_only: true
      - type: bind
        source: ${APPDATA:-${HOME}/.aspnet/https}
        target: /home/app/.aspnet/https:ro
        read_only: true
    networks:
      - dms-net

  web-ui:
    build:
      context: ./web-ui
    ports:
      - "80:80"
    networks:
      - dms-net

networks:
  dms-net:
    driver: bridge
