name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Project
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Step 3: Restore Dependencies
      - name: Restore Dependencies
        run: dotnet restore ./WebApi/WebApi/WebApi.csproj

      # Step 4: Build the Project
      - name: Build Project
        run: dotnet build ./WebApi/WebApi/WebApi.csproj --configuration Release

      # Step 5: Run Unit Tests
      - name: Run Unit Tests
        run: dotnet test ./WebApi/WebApi/WebApi.csproj --no-build --configuration Release
